language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install coveralls --use-mirrors
  - pip install . --use-mirrors
script:
  - coverage run --source=kinopoisk ./kinopoisk/tests.py
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - ramusus@gmail.com
    on_success: change
    on_failure: change
