language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install flake8
  - pip install coveralls --use-mirrors
  - pip install . --use-mirrors
before_script:
  - flake8 .
script:
  - coverage run --source=kinopoisk -m kinopoisk.tests
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - ramusus@gmail.com
    on_success: change
    on_failure: change
